<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <PackageReference Include="NLog" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PlayingCards.Durak\PlayingCards.Durak.csproj" />
    <ProjectReference Include="..\PlayingCards.Server.Core\PlayingCards.Server.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Using Include="PlayingCards.Core" />
    <Using Include="PlayingCards.Server.Core" />
  </ItemGroup>

</Project>
